
export const CopyHTML = (name: string) => {
  const html = `<p>Olá ${name},<br><br>Cansado de campanhas demoradas e trocas de e-mails intermináveis para se conectar com influenciadores? A InfluenceHub está aqui para ajudar!<br><br>Somos uma plataforma centralizada que conecta marcas a influenciadores, oferecendo uma solução completa para impulsionar suas campanhas de marketing de influência. Gerencie suas mídias sociais, encontre influenciadores relevantes e obtenha resultados excepcionais - tudo em um só lugar.<br><br>
  Simplificamos sua estratégia de marketing de influência. Encontre influenciadores, negocie contratos e acompanhe o progresso das colaborações em tempo real. Nosso ambiente intuitivo oferece análises detalhadas para decisões estratégicas e sucesso.<br><br>E influenciadores, não se preocupem! Também temos muito a oferecer. Amplie seu alcance, estabeleça parcerias de sucesso e impulsione sua carreira. Acesse métricas detalhadas, analise o engajamento e conecte-se a marcas relevantes.<br><br>Vamos conversar? Complete o formulário em nosso site para saber como a InfluenceHub pode ajudar sua marca a se conectar com influenciadores e alavancar suas campanhas. Juntos, podemos alcançar resultados excepcionais.<br><br>Aproveite o poder do marketing de influência com a InfluenceHub. <a href="https://influencehub.vercel.app/forms">Clique aqui</a> para saber mais.<br><br>Atenciosamente,<br>Equipe InfluenceHub</p>`;

  return html;
}

export const CopyText = (name: string) => {
  const text = `Olá ${name}!\n\nCansado de campanhas demoradas e trocas de e-mails intermináveis para se conectar com influenciadores? A InfluenceHub está aqui para ajudar!\n\nSomos uma plataforma centralizada que conecta marcas a influenciadores, oferecendo uma solução completa para impulsionar suas campanhas de marketing de influência. Gerencie suas mídias sociais, encontre influenciadores relevantes e obtenha resultados excepcionais - tudo em um só lugar.\n\nSimplificamos sua estratégia de marketing de influência. Encontre influenciadores, negocie contratos e acompanhe o progresso das colaborações em tempo real. Nosso ambiente intuitivo oferece análises detalhadas para decisões estratégicas e sucesso.\n\nE influenciadores, não se preocupem! Também temos muito a oferecer. Amplie seu alcance, estabeleça parcerias de sucesso e impulsione sua carreira. Acesse métricas detalhadas, analise o engajamento e conecte-se a marcas relevantes.\n\nVamos conversar? Complete o formulário em nosso site para saber como a InfluenceHub pode ajudar sua marca a se conectar com influenciadores e alavancar suas campanhas. Juntos, podemos alcançar resultados excepcionais.\n\nAproveite o poder do marketing de influência com a InfluenceHub. Visite: https://influencehub.vercel.app/forms para saber mais.\n\nAtenciosamente,\nEquipe InfluenceHub`;

  return text;
}
